name: Publish DataTableQueryBuilder.DataTables to NuGet


on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.408
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish DataTableQueryBuilder.DataTables
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/DataTableQueryBuilder.DataTables/DataTableQueryBuilder.DataTables.csproj
        PACKAGE_NAME: DataTableQueryBuilder.DataTables
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
